### ISSUE TITLE
Proxy blocked by Discord

### ISSUE THREAD

**Issue by callumisdumb** [hyra-io/Discord-Webhook-Proxy#14]
Proxy has been blocked by Discord.

**Comment by callumisdumb** [comment]
Made some changes on a fork and hosted it on https://hooks.callum.live/, seems to be working on my fork but not on Hyra? Might want to look over the changes I made:
https://github.com/callumisdumb/Discord-Webhook-Proxy

**Comment by Sam512** [comment]
Proxy has not been banned by Discord. 

No useful changes have been made on your fork.

**Comment by callumisdumb** [comment]
Interesting @Sam512, apparently requests to the proxy arent going through to Discord from Roblox, not sure if you'll have any ideas?
