### ISSUE TITLE
Remove Gavin Martin from Contributors

### ISSUE THREAD

**Issue by kvyuaiss** [hyra-io/Discord-Webhook-Proxy#4]

**Comment by kvyuaiss** [comment]
@Sam512 @realgavinmartin

**Comment by Sam512** [comment]
Contributors cannot be removed. If you make a PR and it is approved, you will become a contributor. This is how GitHub works.

**Comment by kvyuaiss** [comment]
thetruthbehindthecontributors@gmail.com

**Comment by kvyuaiss** [comment]
Also can I get access to Sam512/Hyra?

**Comment by kvyuaiss** [comment]
@Sam512
